# Vagrant.configure("2") do |config|
#   config.vm.box = "gusztavvargadr/windows-server-2022-standard"
#   config.vm.communicator = "winrm"
#   config.winrm.username = "vagrant"
#   config.winrm.password = "vagrant"

#   config.vm.hostname = "universo-server"
#   config.vm.network "private_network", ip: "192.190.90.12"

#   config.vm.provider "virtualbox" do |vb|
#     vb.gui = true
#     vb.memory = 4096
#     vb.cpus = 2
#   end

#   config.vm.synced_folder ".", "C:/vagrant"

#   config.vm.provision "shell", path: "setup.ps1", privileged: false
# end

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  
  # Configurar rede
  config.vm.network "private_network", ip: "192.190.90.12"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3333, host: 3333
  
  # Configurar recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  
  # Provisionar com PowerShell
  config.vm.provision "shell", 
    path: "setup.ps1",
    powershell_elevated_interactive: false,
    powershell_args: "-ExecutionPolicy Bypass"
end

